import 'package:environment_quiz/models/quiz_question.dart';

// Correct answer must always be the first option
List<QuizQuestion> questions = [
  QuizQuestion(
    question: 'Which country currently emits the most greenhouse gases?',
    options: [
      'China',
      'Russia',
      'USA',
      'Germany',
    ],
    info: 'China surpassed the USA in 2006/7',
  ),
  QuizQuestion(
    question: 'How much of the world\'s water is available for human use?',
    options: [
      'Less than 1%',
      '15%',
      '35%',
      '75%',
    ],
    info:
        '3% of the earth\'s water is fresh. 2.5% of the earth\'s fresh water is unavailable: locked up in glaciers, polar ice caps, atmosphere, and soil; highly polluted; or lies too far under the earth\'s surface to be extracted at an affordable cost. 0.5% of the earth\'s water is available fresh water.',
  ),
  QuizQuestion(
    question: 'What is the most common type of waste that litters our oceans? ',
    options: [
      'Cigarettes',
      'Food packaging',
      'Plastic bags',
      'Glass bottles',
    ],
    info:
        'Volunteers for the International Coastal Cleanup removed nearly two million cigarettes and cigarette filters in their most recent effort to clear litter from the world\'s oceans.',
  ),
  QuizQuestion(
    question: 'Global warming is caused ...',
    options: [
      'Both by human and natural factors',
      'Mainly by natural factors',
      'Only by natural factors',
      'Only by human activity',
    ],
    info:
        'Both natural and human factors contribute to the changes of the Earth\'s climate. According to the U.S. Geological Survey (USGS), the world’s volcanoes generate about 200 million tons of carbon dioxide (CO2) annually, while our automotive and industrial activities cause some 24 billion tons of CO2 emissions every year worldwide. Despite the arguments to the contrary, the facts speak for themselves: Greenhouse gas emissions from volcanoes comprise less than one percent of those generated by today’s human endeavors.',
  ),
  QuizQuestion(
    question:
        'How long does it take for carbon dioxide (CO2) in the atmosphere to disperse?',
    options: [
      '100 years',
      '500 years',
      '50 years',
      '10 years',
    ],
    info:
        'Even if we stopped sending CO2 into the atmosphere, our past actions would still affect the planet for decades to come.',
  ),
  QuizQuestion(
    question:
        'During the 150 years of the industrial age, the atmospheric concentration of carbon dioxide has increased by ...',
    options: [
      '31%',
      '45%',
      '58%',
      '67%',
    ],
    info:
        'During the 150 years of the industrial age, the atmospheric concentration of carbon dioxide has increased by 31%. This increase can be attributed to various human activities such as burning fossil fuels, deforestation, and industrial processes. These activities release large amounts of carbon dioxide into the atmosphere, contributing to the greenhouse effect and climate change. The 31% increase in carbon dioxide concentration highlights the significant impact of human activities on the Earth\'s atmosphere and the urgent need for sustainable practices to mitigate further increases.',
  ),
  QuizQuestion(
    question:
        'While many greenhouse gases occur naturally and are needed to create the greenhouse effect that keeps the Earth warm enough to support life, ... is the main source of excess greenhouse gases in the atmosphere.',
    options: [
      'Human use of fossil fuels',
      'Deforestation',
      'Factory farming',
      'Population growth',
    ],
    info:
        'By driving cars, using electricity from coal-fired power plants, or heating our homes with oil or natural gas, we release carbon dioxide and other heat-trapping gases into the atmosphere.',
  ),
  QuizQuestion(
    question: 'Global warming may ...',
    options: [
      'All answers are correct',
      'Influence the length of the seasons',
      'Cause coastal flooding',
      'Lead to more frequent and severe storms',
    ],
    info:
        'As the concentration of greenhouse gases grows, more heat is trapped in the atmosphere and less escapes back into space. This increase in trapped heat changes the climate and alters weather patterns.',
  ),
  QuizQuestion(
    question: 'How long does it take for glass to decompose?',
    options: [
      'One million years',
      '100 years',
      'About 500 years',
      '1000 years',
    ],
    info: 'This means that glass can be recycled an infinite amount of times.',
  ),
  QuizQuestion(
    question:
        'To create just 1 kilogram of consumer goods, manufacturers create ... kilograms of waste. ',
    options: [
      '5',
      '7',
      '3',
      '1',
    ],
    info:
        'To create just 1 kilogram of consumer goods, manufacturers create 5 kilograms of waste. This means that for every unit of consumer goods produced, there is a significant amount of waste generated. This waste could be in the form of byproducts, packaging materials, or other types of waste generated during the manufacturing process. The high ratio of waste to consumer goods highlights the environmental impact and inefficiency of the manufacturing process.',
  ),
  QuizQuestion(
    question:
        'Rainforests once covered 14% of the earth\'s land surface; now they cover .... ',
    options: [
      '6%',
      '8%',
      '10%',
      '12%',
    ],
    info:
        'The correct answer is 6%. This suggests that rainforests have significantly decreased in coverage over time, from 14% to just 6% of the earth\'s land surface. This decline in rainforest coverage is a result of deforestation, climate change, and human activities such as logging and agriculture. The loss of rainforests is concerning because they are vital ecosystems that support a wide variety of plant and animal species, as well as provide important ecological services such as carbon sequestration and regulation of the water cycle.',
  ),
  QuizQuestion(
    question:
        '... plant, animal and insect species are being lost every single day due to rainforest deforestation. ',
    options: [
      '137',
      '100',
      '168',
      'More than 200',
    ],
    info:
        'The statement mentions that plant, animal, and insect species are being lost every single day due to rainforest deforestation. The answer "137" implies that 137 species are being lost every day. This number is within the given range of options and is a plausible estimate considering the extent of rainforest deforestation and its impact on biodiversity.',
  ),
  QuizQuestion(
    question:
        'What year did the United States EPA declare greenhouse gasses a threat to public health?',
    options: [
      '2009',
      '1973',
      '1984',
      '1999',
    ],
    info:
        'After a thorough examination of the scientific evidence and careful consideration of public comments, in 2009 the U.S. Environmental Protection Agency (EPA) announced that greenhouse gases (GHGs) threaten the public health and welfare of the American people.',
  ),
  QuizQuestion(
    question: 'What is the most common type of trash thrown away by Americans?',
    options: [
      'Paper products and cardboards',
      'Plastic bags',
      'Metal',
      'Glass bottles',
    ],
    info:
        'According to recent studies and waste management reports, paper products and cardboard are the most common types of trash generated by Americans. These materials make up a significant portion of municipal solid waste, which includes items like packaging, newspapers, magazines, mail, food and beverage containers, and more.The reason for this is that paper products are widely used in various aspects of daily life, including packaging, printing, and food service. Additionally, cardboard is commonly used in product shipping and retail displays.While other materials like plastic bags, metal, and glass bottles are also frequently thrown away, they do not compare to the sheer volume of paper and cardboard waste generated in the United States.',
  ),
  QuizQuestion(
    question:
        'Most of the oil that we use is imported into our country from other nations. The oil is carried in huge sea-going tankers. Sometimes, these tankers get damaged, and the oil leaks into the oceans and seas. What is such an accidental discharge of oil into water bodies called? ',
    options: [
      'Oil spill',
      'Water pollution',
      'Oil leak',
      'Tanker leak',
    ],
    info:
        'Oil on ocean surfaces, which is called an oil spill, is harmful to many forms of aquatic life because it prevents sufficient amounts of sunlight from penetrating and also reduces the level of oxygen dissolved in seawater. Crude oil renders feathers and gills ineffective, so that birds and fish may die from direct contact with the oil itself.',
  ),
  QuizQuestion(
    question: 'What is the leading source of energy in the United States?',
    options: [
      'Oil',
      'Coal',
      'Nuclear power',
      'Natural gas',
    ],
    info: 'Oil provides the U.S. with about 39% of its energy.',
  ),
  QuizQuestion(
    question: 'Petroleum, coal and natural gas are all ...',
    options: [
      'Fossil fuels',
      'Non-polluting',
      'Renewable',
      'Fossil fuels',
    ],
    info: 'All are fossil fuels which are neither ecofriendly nor renewable.',
  ),
  QuizQuestion(
    question:
        'Which of the following greenhouse gases is primarily responsible for trapping heat in the Earth\'s atmosphere?',
    options: [
      'Cardon dioxide (CO2)',
      'Nitrous oxide (N2O)',
      'Methane (CH4)',
      'Ozone (O3)',
    ],
    info:
        'Carbon dioxide is the most abundant greenhouse gas emitted by human activities such as burning fossil fuels and deforestation. It traps heat in the atmosphere, contributing significantly to global warming and climate change. While other gases like methane and nitrous oxide also contribute to the greenhouse effect, carbon dioxide is the primary driver due to its long-lasting presence in the atmosphere.',
  ),
  QuizQuestion(
    question: 'Which of the following is a major contributor to soil erosion?',
    options: [
      'Deforestation',
      'Recycling',
      'Renewable energy',
      'Urbanization',
    ],
    info:
        'Deforestation, the clearing of forests for agriculture, logging, or urban development, removes vegetation that holds soil in place. Without tree roots and plant cover, soil becomes more susceptible to erosion by wind and water. This leads to loss of fertile topsoil, decreased soil quality, and increased sedimentation in water bodies, impacting ecosystems and agriculture negatively.',
  ),
  QuizQuestion(
    question:
        'How much of our air pollution comes from motor vehicles, like cars and trucks?',
    options: [
      '30%',
      '20%',
      '40%',
      '50%',
    ],
    info:
        'Around 30% of air pollution originates from motor vehicles like cars and trucks. Emissions from these vehicles, including nitrogen oxides, particulate matter, and volatile organic compounds, contribute significantly to air pollution, impacting air quality and public health, especially in urban areas with high traffic congestion.',
  ),
];
